name: 'Semgrep Reporting'
description: 'Report Semgrep findimgs to PRs with suggested changes'
author: 'Peter Hoeg Steffensen'
inputs:
  report_path:
    required: true
    description: Path to the json output of the semgrep scan
  github_secret:
    required: true
    description: Action secret
  base_path:
    description: Base path of the checked out repository
runs:
  using: 'node16'
  main: 'dist/index.js'
