name: 'Semgrep reporting'
description: 'Report Semgrep findimgs to PRs with suggested changes'
author: 'Peter Hoeg Steffensen'
inputs:
  report_path:
    required: true
    description: Path to the json output of the semgrep scan
  github_secret:
    required: true
    description: Action secret
  issue_number:
    required: true
    description: PR number to write the report to
  commit_id:
    required: true
  repo:
    required: true
    description: This repository
runs:
  using: 'node16'
  main: 'dist/index.js'
