name: Semgrep Scan
on:
  pull_request: {}
  push:
    branches: ["master", "main"]
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan
        run: semgrep --config "p/eslint-plugin-security" -l ts --json --output=semgrep.json .
      - uses: ./
        with:
          github_secret: ${{secrets.GITHUB_TOKEN}}
          report_path: semgrep.json